version: '3.1'

services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "7017:27017"
    restart: unless-stopped
    env_file:
      - ./nodejs/.env
    volumes:
       - ./mongodb/suggestion_data:/data/db